# Generated by Django 5.2.8 on 2025-11-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cardamom', 'Cardamom'), ('Clove', 'Clove'), ('Cinnamon', 'Cinnamon'), ('Pepper', 'Black Pepper'), ('Other', 'Other')], default='Other', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, null=True, unique=True),
        ),
    ]
