# Generated by Django 5.2.4 on 2026-01-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_contactmessage_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorregistration',
            name='company',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='visitorregistration',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
